Added a reference to Scapy topic.
secdev/awesome-scapy pull request #11
Opened 2021-10-03 09:39 UTC by Joe-Sin7h

I have added an reference to scary topic under MISC section as asked [here](https://github.com/secdev/scapy/pull/3382#issuecomment-932888168)

2021-10-03 09:39 UTC, Joe-Sin7h commented
@guedou could you please review it. Thank you.

2021-10-03 12:29 UTC, guedou requested changes

2021-10-03 12:29 UTC, guedou commented on README.md
> +- [scapy-topic](https://github.com/topics/scapy): Scapy topic on GitHub explore.
I will rather have:
```
- [Explore Scapy topics](https://github.com/topics/scapy) on GitHub
```

2021-10-03 12:43 UTC, Joe-Sin7h commented on README.md
> +- [scapy-topic](https://github.com/topics/scapy): Scapy topic on GitHub explore.
done 👍🏻

2021-10-10 15:34 UTC, joesinghh commented
@guedou could you please merge it as `github/explore` has merged my PR.

2021-10-11 07:23 UTC, merged